name: Export User Data

on:
  schedule:
    - cron: '0 0 * * 0' 

jobs:
  export_and_post:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo slack_sdk

    - name: Export user data and post on Slack
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        DB_NAME: ${{ secrets.DB_NAME }}
        COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      run: |
        python export_user_data.py
